#  numpy.array操作

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

# list的缺点，相对于numpy



In [3]:
l=[i for i in range(10)]     #
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
l[5]="machine learn"

In [5]:
l             #(list)各数据类型可以是不同的，但是速度低下

[0, 1, 2, 3, 4, 'machine learn', 6, 7, 8, 9]

In [6]:
import array
a=array.array('i',[i for i in range(10)])
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[5]=1233    #速度很快，灵活想不行，没有向量，矩阵运算，不行

#  numpy.array


In [8]:
a=np.array( range(10) )    #  构建了一个矩阵
a[1]=100                   # 也不行 数据类型 要一致
a

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [9]:
a.dtype

dtype('int32')

In [10]:
a[1]=5.8    #会进行类型转换，转换为int
a   


array([0, 5, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a2=np.array([i for i in range(10)])   #大多需要double 类型的
print(a2.dtype)       
print(a2)   

int32
[0 1 2 3 4 5 6 7 8 9]


# 创建numpy.array  可以转化为多维数组 
#### 1.np.array( range(10) )
#### 2.np.array([1,23,4,5])
#### 3.np.array([i for i in range(10)])


## np.() .reshape(x,y,z,..), 条件是xyz..的乘积等于
## 元素的数量，就转化了

## 接下来也有很多创建array的方法

In [12]:
np.zeros(10,dtype=int)    #是一个一维的向量，

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 创建二维矩阵，向量

In [13]:
np.zeros([3,3],dtype=int)   #得到一个矩阵，
#前面的那个东西是 shape,NxM  规模的一个矩阵

np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,6)) # 元组

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.full(shape=(4,4),fill_value=444.1)   #全都是有参数

array([[444.1, 444.1, 444.1, 444.1],
       [444.1, 444.1, 444.1, 444.1],
       [444.1, 444.1, 444.1, 444.1],
       [444.1, 444.1, 444.1, 444.1]])

### arange 创建np.array 数组 ，.reshape()，转化为多维数组

In [16]:
# 新的方法  arange
np.arange(0,20,2.3)  #可以是浮点数，以为数组

array([ 0. ,  2.3,  4.6,  6.9,  9.2, 11.5, 13.8, 16.1, 18.4])

### linspace创建np.array 数组，第三个参数不是步长，是几个点

In [17]:
np.linspace(0,20,11 )   #更长的截取出 10个点，起始点和终止点都在的，浮点数


array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random 模块

In [18]:
np.random.randint(4,8,size=(3,5)) #前闭后开区间，来一个参数以免混淆
# 传进去一个元组，创建二维的  

array([[7, 7, 7, 7, 4],
       [4, 6, 6, 4, 5],
       [5, 7, 5, 5, 6]])

## 随机数种子，当我们多次需要这个随机数生成的
## 矩阵时候，我们写出
## np.random.seed(xxx)

In [19]:
np.random.randint(4,8,size=(3,5)) 

array([[6, 6, 5, 5, 6],
       [4, 7, 4, 6, 4],
       [6, 7, 4, 5, 6]])

In [20]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5)) 

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [21]:
np.random.random((3,3))  #random random 随机数字，浮点型数据,矩阵

array([[0.28116849, 0.46284169, 0.23340091],
       [0.76706421, 0.81995656, 0.39747625],
       [0.31644109, 0.15551206, 0.73460987]])

In [22]:
np.random.random((3,10))

array([[0.73159555, 0.8578588 , 0.76741234, 0.95323137, 0.29097383,
        0.84778197, 0.3497619 , 0.92389692, 0.29489453, 0.52438061],
       [0.94253896, 0.07473949, 0.27646251, 0.4675855 , 0.31581532,
        0.39016259, 0.26832981, 0.75366384, 0.66673747, 0.87287954],
       [0.52109719, 0.75020425, 0.32940234, 0.29130197, 0.00103619,
        0.6361797 , 0.97933558, 0.91236279, 0.39925165, 0.40322917]])

###  正态分布

In [23]:
np.random.normal(0,1,size=(5,5))  #指定均值和方差,元组

array([[ 1.23174866, -0.91360034, -0.27084407,  1.42024914, -0.98226439],
       [ 0.80976498,  1.85205227,  1.67819021, -0.98076924,  0.47031082],
       [ 0.18226991, -0.84388249,  0.20996833,  0.22958666,  0.26307642],
       [ 2.16633222, -1.04887593, -1.84768442,  0.53401503, -1.19574802],
       [-0.28915737, -0.24332703, -0.74266653,  1.20790511,  1.02787711]])

### numpy pandas 是使用c语言写的，所以速度是很快的，还有支持很多的矩阵运算，

array([1, 2, 3, 4])