## 向量的加法，一组值变为一个值，求和



In [12]:
import numpy as np
l=np.random.random(100)
print(l)


[0.49688364 0.45040897 0.28820977 0.79804334 0.7271959  0.15058876
 0.17359108 0.43035616 0.61097619 0.41913773 0.36265052 0.80001628
 0.44607693 0.53074753 0.95708205 0.13858901 0.92609202 0.29241659
 0.90066962 0.05965671 0.43879349 0.07233699 0.4281122  0.90426383
 0.41035766 0.00466003 0.51944638 0.82751329 0.7628935  0.82241543
 0.53523258 0.89582734 0.06817698 0.65106002 0.99007667 0.74629447
 0.69516923 0.37254481 0.00657203 0.19582312 0.77760085 0.37099995
 0.82265159 0.04006417 0.60074    0.01301796 0.27919606 0.25038549
 0.66126134 0.92816575 0.33060128 0.32194387 0.60524113 0.98118415
 0.43065674 0.14916214 0.90683186 0.73005529 0.80940746 0.88377522
 0.19507479 0.67838017 0.18317804 0.90959463 0.97500841 0.37773793
 0.27949872 0.77876878 0.897717   0.25061385 0.92175239 0.45559665
 0.93825861 0.69368822 0.25637224 0.85718472 0.80277904 0.15836961
 0.32498065 0.86668663 0.0867355  0.53646755 0.77061549 0.89546304
 0.70469148 0.77452196 0.51474915 0.96138615 0.51936695 0.2473

In [16]:
print(sum(l))
print(np.sum(l))

54.13800366778979
54.13800366778979


### sum操作，进行求和操作
#### sum和 np.sum 其中的速率np.sum   是很快的

In [20]:
big=np.random.rand(1000000)
%time sum(big)
%time np.sum(big)


Wall time: 198 ms
Wall time: 2.99 ms


500459.5158504846

####   一个数组中的最小值 ，最大值
#### np.min()  np.max()
#### x.min() x.max()

In [27]:
print( np.min(big) )
print( np.max(big)) 

1.764640832346842e-07
0.9999991016653249


### 二维矩阵的聚合运算
#####   sum （所以元素进行加法求和）

In [33]:
x=np.arange(16).reshape(4,-1)
print(x)

np.sum(x)   #就是二维矩阵所有的元素进行加法运算


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


120

#### 每一行的和
#### 每一列的和

In [40]:
print(np.sum(x,axis=0))   #每一列的和
print(np.sum(x,axis=1))    #每一行的和

[24 28 32 36]
[ 6 22 38 54]


####  矩阵元素的乘积操作
#### np.prod()

In [45]:
print(np.prod(x+1)) 
print(np.prod(x))

2004189184
0


#### 所有元素的平均值 np.mean()
#### 元素的中位数 np.median()

In [52]:
print(np.mean(x))
print(np.median(x))

7.5
7.5


### 使用 numpy.percentile(xx,q=x%) 百分之多少的数据小于 多少，对于统计有很大的意义，


In [58]:
print(big)
print(np.percentile(big,100))  #100 的数据小于小于一个数值，

[0.47254512 0.18426867 0.13593986 ... 0.10686191 0.47331924 0.60051048]
0.9999991016653249


### 机器学习中，有几个数据点
#### 0 25 50 75 100

In [66]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big,percent))

1.764640832346842e-07
0.2508891056835767
0.5006746509422919
0.7503271562583911
0.9999991016653249


#### 方差和标准差
#### np.var() 和np.std()

In [71]:
print(np.var(big))  #方差
print(np.std(big)) #标准差

0.08318071995364887
0.28841067933356573


In [75]:
x=np.random.normal(0,1,size=1000000)
print(x)

[ 1.70903537  0.24078448  0.18288679 ... -0.49055092 -0.37947962
 -1.18199172]


In [79]:
print(np.mean(x))  #均值
print(np.std(x))  #标准差
print(np.var(x))  #方差

0.0001706778129553642
0.9997288180735548
0.999457709686747
