In [1]:
import numpy as np

### np.where()  有两种用法

In [2]:
a=np.array([0,1,2,3,4,10])
a

array([ 0,  1,  2,  3,  4, 10])

#### np.where(condition)  满足条件的输出 下标索引， 原数组是几维数组，输出也是几维数组

In [3]:
np.where(a>=5)

(array([5], dtype=int64),)

#### np.where(condition,x,y)   满足条件输出x，否则 y, 也是原数组几维数输出几维数

In [4]:
np.where(a>1,1,-1)  

array([-1, -1,  1,  1,  1,  1])

#### 使用np.where 找出数组中满足条件的 元素数量

In [10]:
print(a)
print(sum(np.where(a>=1,1,0)) )

[ 0  1  2  3  4 10]
5


#### 或者使用Counter 找出数数量 

In [15]:
from collections import Counter
print( Counter(a>=1)[True] )   #  返回一个字典

5
