### 合并
### concatenate 操作
#### 其中可以有多个矩阵合并



In [1]:
import numpy as np
x1=np.array([1,2,3])
x2=np.array([3,4,5])
ans=np.concatenate( [x1,x2]  )
x3=np.array([666,666,666])
ans=np.concatenate([ans,x3,x1,x2])   #进行合并
print(ans)      


[  1   2   3   3   4   5 666 666 666   1   2   3   3   4   5]


### 多维的矩阵    concatenate([x,x..],axis)   两个参数， axis是一个依据不同的轴来合并的，0是第一个维度，1是第二个，依次向后排，重要
#### 1.行合并 ，增加了数据量 
#### 2.列合并 ，增加了特征量
##  以上的不同区别，数据最多是  二维的形式出现

In [2]:
a=np.array([[1,2,3,4],    # 3X4
            [2,3,4,5],
            [6,7,8,9],
           ])
print(  np.concatenate([a,a])   )   #连接到了后面，成为了6X4的 二维矩阵

[[1 2 3 4]
 [2 3 4 5]
 [6 7 8 9]
 [1 2 3 4]
 [2 3 4 5]
 [6 7 8 9]]


In [3]:
b=np.concatenate([a,a],axis=1)    #  实现了列合并
print(b)

[[1 2 3 4 1 2 3 4]
 [2 3 4 5 2 3 4 5]
 [6 7 8 9 6 7 8 9]]


#### 以上是相同的矩阵进行合并
#### 下面是进行合并不相同的矩阵

In [4]:
b=np.array([[1,2,3],
           [1,2,3],
           [1,2,3]
           ]) 
print(b,end='\n\n')
c=np.array([1,2,3])

ans=np.concatenate([b,c.reshape(1,-1)])   # 看来是需要进行一些操作 将数据转化为 矩阵
print(ans)

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


## np.vstack 竖直方向上合并,   两矩阵的列是相等的
## np.hstack 水平方向上合并，两矩阵的行是相等的
##  注意上面的规则

In [5]:
c=np.array([888,888,888])   #h是水平的，矩阵行要相等，列可以不相等 
b=np.array([1,2,3,45,6])
np.hstack([b,c])    


array([  1,   2,   3,  45,   6, 888, 888, 888])

In [6]:
b=np.array( [[1,2,3],         #n是数值，矩阵的列要相等，行可以不同  ，但是列是要求相同的
            [9,9,9],
            [8,8,8]
            ] )
c=np.array([[2,3,4],
           [111,111,111]])
np.vstack([b,c])


array([[  1,   2,   3],
       [  9,   9,   9],
       [  8,   8,   8],
       [  2,   3,   4],
       [111, 111, 111]])

##  分割操作
#### split()  操作，左闭右开的，其实是按照数量来分的，不是矩阵中的数据，注意 


In [7]:
np.random.seed(777)            #  切割操作，  
x=np.random.randint(1,10,10)   #随机生成矩阵   ，其中的操作
print(x)
np.split(x,[2,5])              #  是左闭右开的分割规则，不要弄错了，注意
# print(np.split(x, [2,5]))    #  这个list 其中装的，是分割的下标，n个分割点分为 n+1 段操作

[8 7 8 2 8 5 8 9 8 3]


[array([8, 7]), array([8, 2, 8]), array([5, 8, 9, 8, 3])]

####  一维矩阵的操作，一下是多维矩阵
#### 分割的形式，默认是竖直方向的，行分割的，即 第一个维度 0

In [18]:
a=np.array([[1,2,3],                    
           [3,4,5],
            [6,7,8],
           [1,13,123]
           ])
x1,x2=np.split(a,[2])       #按照竖直进行 分割的，默认是按照 竖直进行切割，也是 以坐标来划分的
print(x1,x2,sep='\n\n')

[[1 2 3]
 [3 4 5]]

[[  6   7   8]
 [  1  13 123]]


In [9]:
x1=np.arange(16).reshape(4,4)
print(x1)

print(np.split(x1,[2]))     #上面两行，剩下的是第二个
print(np.split(x1,[3]))     # 上面是三个，下面是剩下的

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


#### 水平方向上 列的分割，axis=1


In [10]:
print(x1)
print(np.split(x1,[2],axis=1))   #第二个维度，即1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


### 根据上面合并，分割也有两个东西
#### vsplit 是垂直方向上  hsplit 是水平方向上

In [11]:
print(x1)
print(np.vsplit(x1,[2]))   #上两个为一个，剩下的为一个
print('--------------------')
print(np.hsplit(x1,[3]))   #前三个为一个，剩下的为一个


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
--------------------
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [12]:
print(x1,end="\n\n")
data,label =np.hsplit(x1,[-1])   #这里将最后一列拿下来，简单的写法
print(data,end="\n\n")
print(label)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]

[[ 3]
 [ 7]
 [11]
 [15]]


In [13]:
print(  label[:,0] )  #从矩阵中抽出 一个向量

[ 3  7 11 15]


In [14]:
a=np.array([1,2,3,4])
b=np.arange(16).reshape(4,4)
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### .T转置 对于一维的数组是不行的，需要二维以上的矩阵，所以是不对的
####  np.transpose 也是不行的

In [34]:
a=np.array([[1,2],
            [3,4],
            [1,2]
            
])
b=np.array([[1,2]]).reshape(-1)

print(a)
print(a.T)   # 

[[1 2]
 [3 4]
 [1 2]]
[[1 3 1]
 [2 4 2]]


In [37]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
a.reshape(-1)   # 就是一个向量   

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])