###  二维切片有点难受
### 二维数组，矩阵，row columns 之间由,隔开，行和列都是可以使用切片处理的，还有一些 索引的array数组

In [1]:
import numpy as np

In [2]:
a=np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [3]:
a[3]

3

#### 使用切片很重要，使用切片输出等间距的数据
#### 但是任意间距的也是可以输出的
####   定义一个 a[x1,x2,x3...]  ,    b[a] ，就可以输出自己选中的数据

In [4]:
b=[1,2,6]
print(a[b])

[1 2 6]


#### 二维的索引是，可以使用在一维，二维中使用
#### 1. a[16] 是一维数组，b[[]] 是二维数组，存放着索引位置，然后输出a[b]，将会按照b的形式输出索引下的数据
#### 2.  或者在多维数组中使用一维数组


In [5]:
np.random.seed(100)
a=np.random.randint(10,size=(10))
print(a)
ind= np.array([
    [0,2],
    [1,3]
])
 
print(ind)
print('------')
print(a[ind])


[8 8 3 7 7 0 4 2 5 2]
[[0 2]
 [1 3]]
------
[[8 3]
 [8 7]]


#### row=np.array([1,2])
#### col=np.array([1,2])
#### print(a[row,col])    输出  a[1,1]  a[2,2]元素数据
#### 还有按照自己 方法拿出 行和列中的元素
####  还有很重要一点是，在多维上的矩阵上，a[1,x], 我们取得是第一行的东西，或者第一列的东西

In [6]:
a=np.random.randint(16,size=(4,4))
print(a)
row=np.array([1,3 ])    #  不是切片，就是一个  索引
col=np.array([1,3 ])   
print(a[row,col])     #  python   真是很容易上手的，

[[ 2 14  2  1]
 [ 0  8 15  4]
 [11 12 10  0]
 [11  9 13  6]]
[8 6]


In [7]:
print(a)
print('-------')

#垂直方向上 分开
print(a[0,col])   #  这个也是挺难的，二维的东西，其中的索引
print(a[:2,col])  # 二维矩阵的 东西  上可以使用切片处理的方法，更加高效

[[ 2 14  2  1]
 [ 0  8 15  4]
 [11 12 10  0]
 [11  9 13  6]]
-------
[14  1]
[[14  1]
 [ 8  4]]


In [8]:
print(a)

#按照水平方向上，分割 
print( a[col,:]   ) #   a[:,:]  二维的


[[ 2 14  2  1]
 [ 0  8 15  4]
 [11 12 10  0]
 [11  9 13  6]]
[[ 0  8 15  4]
 [11  9 13  6]]


####  矩阵操作对于bool运算来说也是可以的，应用在机器学习中很重要

In [9]:
boola=[True,False,True,True]       #
print(a[:2,boola])

[[ 2  2  1]
 [ 0 15  4]]


## numpy.array 的批量比较*****，是其中所有的东西都会进行比较的

In [10]:
x=np.arange(3,10)   #  是一个范围
print(x)

[3 4 5 6 7 8 9]


In [11]:
x<=3

array([ True, False, False, False, False, False, False])

In [12]:
x>3

array([False,  True,  True,  True,  True,  True,  True])

In [13]:
x==3 

array([ True, False, False, False, False, False, False])

In [14]:
x!=3

array([False,  True,  True,  True,  True,  True,  True])

In [15]:
2*x==24-4*x    #这个是一个方程式，对于一维数组当中所有的数据来说

array([False,  True, False, False, False, False, False])

### 对于多维矩阵，其中每一个元素都要进行比较

In [16]:
a=np.random.randint(10,size=(3,3))
print(a)
print(a<6)

[[2 4 1]
 [5 3 4]
 [4 3 7]]
[[ True  True  True]
 [ True  True  True]
 [ True  True False]]


In [17]:
x=np.array(range(16))
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


#### 底下这个，np.sum()   ,将true 作为了1，false作为了0,所以sum 可以表示有几个是 true的

In [18]:
np.sum(x<=3)   

4

####  np.count_nonzero() ,输出非0的东西

In [19]:
np.count_nonzero(x<=3)

4

In [20]:
 np.any(x==0)    #是否有为0的元素,只要有0，就是true

True

In [21]:
np.all(x>=0)   #all 与 any  之间的差距是一个是只要有 ，一个是全都是

True

### 二维的操作

In [22]:
print(a)

[[2 4 1]
 [5 3 4]
 [4 3 7]]


In [23]:
print(np.sum(a%2==0))   #进行计数操作，搭配到 比较操作

4


#### axis=1 按照水平方向上进行操作，就是按照水平的方向进行操作
#### axis=0 按照垂直方向上进行操作，在竖直的方向上进行操作

In [24]:
print( np.sum(a%2==0,axis=1)  )     #每一行的数据，返回一个 array   

[2 1 1]


In [25]:
print(np.sum(a%2==0,axis=0))      #每一列的数据

[2 1 1]


In [26]:
print(np.all(a>0,axis=1))   #  按照水平的东西

[ True  True  True]


In [27]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
print(np.sum((x>3) & (x<10)))    #这个运算符一定要记住，位运算
print(np.sum((x%2==0)| (x%3==0)))  #或者运算符号

6
11


In [29]:
np.sum(~(x!=0))   #取非是 ~号,   取非的操作

1

####  x[x%2==0]  就会输出所有的符合数据

In [30]:
x[x<5]  

array([0, 1, 2, 3, 4])

In [35]:
print(a)

[[2 4 1]
 [5 3 4]
 [4 3 7]]


#### 数据处理很好

In [41]:
a[ a[:,2]%2==0,: ].reshape(a[ a[:,2]%2==0,: ].size)   #最后转化为  一个向量， 不是矩阵了，还是不错的



array([5, 3, 4])

#### pandas #进行预处理