In [1]:
import numpy as np

###  在list中, a*2 为其中的 元素 重复两次，不是变为两倍

In [2]:
a=[i for i in range(0,10)]
print(a*2)   # 只是将所有的元素重复了一遍

#实现将所有的数据变为2倍
for i in range(10):
    a[i]=a[i]*2
print(a)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [3]:
%%time
a=[i*2 for i in range(1000000)]

Wall time: 246 ms


## 使用 numpy实现

In [4]:
%%time
a=np.array(2*i for i in range(1000000))         

Wall time: 36.1 ms


###  速度确实是快速，然后就是

In [5]:
l=[i for i in range(1000000)]

In [6]:
%%time
a=2*l

Wall time: 31.9 ms


In [7]:
%%time
now1=np.array(i*2 for i in range(1000000))
'''
array([1,2,3,4,5])
array(range(1000000))
array(i for i in range(1000000))
'''



Wall time: 0 ns


'\narray([1,2,3,4,5])\narray(range(1000000))\narray(i for i in range(1000000))\n'

## numpy.array 速度优于原生list，进行优化


In [8]:
%%time
now1=2*a


Wall time: 72.6 ms


In [9]:
s1=np.arange(16).reshape(4,4)
s1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 一些基础的计算

In [10]:
print(s1+1)  #加法
print(1/(s1+1))   #1/ 所有的元素
print(s1//2)     #进行取整运算
print(s1%2)      #进行取余运算 
print(s1*2 )     #s1  全部乘
print(np.abs(s1) )    
print(np.sin(s1))     
print(np.cos(s1))   
print(np.tan(s1))   
print(np.exp(s1))  #以e为底的对数，

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1.         0.5        0.33333333 0.25      ]
 [0.2        0.16666667 0.14285714 0.125     ]
 [0.11111111 0.1        0.09090909 0.08333333]
 [0.07692308 0.07142857 0.06666667 0.0625    ]]
[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]
 [6 6 7 7]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]]
[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257 ]
 [ 0.84385396  0.90744678  0.13673722 -0.75968791]]
[[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01]
 [ 1.15782128e+00 -3.38051501e+00 -2.91006191e-01  8.71447983

In [11]:
print(s1)
print(3**s1)          #3为底，
print(np.log(s1+1))   #取对数

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[       1        3        9       27]
 [      81      243      729     2187]
 [    6561    19683    59049   177147]
 [  531441  1594323  4782969 14348907]]
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502  2.77258872]]


## 更强大的是矩阵与矩阵之间的运算


In [12]:
s1=np.arange(10).reshape(2,5)
print(s1)
s2=np.random.randint(1,10,(5,2))
print(s2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[6 6]
 [6 9]
 [6 2]
 [6 3]
 [5 8]]


### + - * / 都要求两个矩阵是完全相同的


In [13]:
#print(s1+s2)
#print(s1-s2)

### 下面这个运算与 线性代数矩阵运算不一样
#### 这个式子是  相等的两个矩阵对应元素相乘，注意

In [14]:
#print(s1*s2)
#print(s1/s2)    #也是相同的运算机制

###  线性代数的标准运算机制， a.np.dot(b)

In [15]:
print(s1.dot(s2))

[[ 56  54]
 [201 194]]


### 矩阵的转置运算

In [16]:
print(s1)
print("--------")
print(s1.T)      #进行转置运算
print("--------")
s1=s1.T
print(s1+s2)    #必须是相同的才可以运算

[[0 1 2 3 4]
 [5 6 7 8 9]]
--------
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
--------
[[ 6 11]
 [ 7 15]
 [ 8  9]
 [ 9 11]
 [ 9 17]]


## 向量和矩阵的运算



#### a(向量)+b(矩阵) ,   运算机制是
#### 1.列数与维数相同
#### 2.矩阵的列数是1，向量的维数可以任意
####   结果是 矩阵全部元素进行加和

In [17]:
a=np.arange(3).reshape(3,1) #  矩阵的列数与维数相同
print('a:',a)
b=np.array([1,2,123])       #是一个向量，不是矩阵，不能使用矩阵的操作

print(a+b)

a: [[0]
 [1]
 [2]]
[[  1   2 123]
 [  2   3 124]
 [  3   4 125]]


#### tile 操作，将一个基本单元进行堆叠，可快速生成矩阵

In [18]:
a=np.tile((1,2,3),(2,2)) 
print(a)

[[1 2 3 1 2 3]
 [1 2 3 1 2 3]]


#### 使用tile 进行向量和矩阵操作

In [19]:
a=[1,2,3,4]
b=np.arange(16).reshape(4,4)
print(np.tile(a,(4,1)))  #对滴
print(b+np.tile(a,(4,1)))  #进行加法了，      

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]
 [13 15 17 19]]


#### 向量与矩阵的乘法
#### 其中的机制也是，列数与维数相同

In [20]:
a=np.array([12,2,3])        
b=np.array(range(3)).reshape(3,1)
print(b)
a*b

[[0]
 [1]
 [2]]


array([[ 0,  0,  0],
       [12,  2,  3],
       [24,  4,  6]])

#### 矩阵与向量的线性代数的乘法，a.dot(b) ，需要列数与维数相同

In [21]:
print(a.dot(b))   #线性代数规则  进行乘法，需要其中列数与行数相同


[8]


In [22]:
a=np.arange(4).reshape(2,2)
b=np.array([1,2])
print(a)
print(b)

[[0 1]
 [2 3]]
[1 2]


###  重要的是，矩阵的逆
#### 方阵才有逆矩阵，  np.linalg.inv()

In [23]:
print(a)
np.linalg.inv(a)   #矩阵的逆，



[[0 1]
 [2 3]]


array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [24]:
print(a.dot(np.linalg.inv(a)))   #单位矩阵

[[1. 0.]
 [0. 1.]]


#### 但是，不是方阵的矩阵有矩阵
#### 是操作， np.linalg.pinv(x)

In [52]:
a=np.arange(0,4).reshape(4,1)
print(a)
print(np.linalg.pinv(a)) 

[[0]
 [1]
 [2]
 [3]]
[[0.         0.07142857 0.14285714 0.21428571]]


In [53]:
print(a.shape) 

(4, 1)


In [60]:
print(a)
x=np.linalg.pinv(a)   #x 就是伪逆矩阵
print(x)

a.dot(x)      # 好像是，有的会出现错误，有的是对的

[[0]
 [1]
 [2]
 [3]]
[[0.         0.07142857 0.14285714 0.21428571]]


array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.07142857, 0.14285714, 0.21428571],
       [0.        , 0.14285714, 0.28571429, 0.42857143],
       [0.        , 0.21428571, 0.42857143, 0.64285714]])