In [1]:
import numpy as np

In [2]:
big=np.random.rand(1000000)    
print(big)

[0.72212506 0.4401707  0.16743516 ... 0.73764304 0.87603659 0.43084607]


### 索引arg,找出位置来
#### args+运算

In [34]:
print(np.argmin(big))  #搜索出一个点的位置
print(np.min(big))
print(big[485964])

485964
1.8873382967576902e-07
1.8873382967576902e-07


In [35]:
print(np.argmax(big)) #  输出最大值位置
print(np.max(big))
print(big[661733])

661733
0.9999974037319129
0.9999974037319129


##  排序和进行索引

In [61]:
np.random.seed(110)
x=np.random.randint(10,size=10)
print(x)

[0 3 9 0 0 0 6 2 8 9]


#### 乱序操作，np.random.shuffle(xx)

In [71]:
np.random.seed(110)
np.random.shuffle(x)
x

array([0, 0, 8, 0, 3, 9, 6, 9, 2, 0])

#### 排序操作，sort ，但是不会对原来的数组造成影响
#### 但是如果我们希望 对原来数组进行修改的话，需要使用x.sort()

In [7]:
x=np.sort(x)
print(x)

[0 0 0 0 2 3 6 8 9 9]


In [8]:
np.random.shuffle(x)
print(x)

[0 2 0 3 9 6 0 0 8 9]


In [9]:
print(x)
x.sort()
print(x)

[0 2 0 3 9 6 0 0 8 9]
[0 0 0 0 2 3 6 8 9 9]


In [10]:
now=np.random.randint(10,size=(4,4))
print(now)


[[0 5 5 2]
 [2 3 6 4]
 [0 1 7 3]
 [1 5 5 3]]


####   对于二维的矩阵，排序默认是按照行排序的，按照1轴
####   想要按照列来排序，axis=0

In [11]:
print(np.sort(now)  )
now.sort()


[[0 2 5 5]
 [2 3 4 6]
 [0 1 3 7]
 [1 3 5 5]]


In [12]:
print(np.sort(now,axis=1))
print(np.sort(now,axis=0))


[[0 2 5 5]
 [2 3 4 6]
 [0 1 3 7]
 [1 3 5 5]]
[[0 1 3 5]
 [0 2 4 5]
 [1 3 5 6]
 [2 3 5 7]]


In [13]:
#np.random.shuffle(x)
#x.sort()
print(x)


[0 0 0 0 2 3 6 8 9 9]


####  这个意思就是一点是，np.argsort()  排完序后，按照排完序后的数据来看在原数组中是第几个，如果已经是完全有序的，那就按照0~9 开创建数组了

In [14]:
print(np.argsort(x))

[0 1 2 3 4 5 6 7 8 9]


####  按照要求，找到比某个值小的数据就行，
####  np.partition(x,num)   操作完成，就将符合数据放到左边

In [15]:
np.random.seed(100)
a=np.random.randint(10,size=10)
print(a)
print(np.partition(a,5))

[8 8 3 7 7 0 4 2 5 2]
[2 0 2 3 4 5 7 8 7 8]


In [16]:
print(np.argpartition(a,5))  #找出在原数组的下标位置

[7 5 9 2 6 8 4 1 3 0]


#### 对于二维的矩阵，也是可以使用索引位置的

In [17]:
print(now)

[[0 2 5 5]
 [2 3 4 6]
 [0 1 3 7]
 [1 3 5 5]]


In [18]:
np.random.seed(666)
np.random.shuffle(now)
print(now)

[[1 3 5 5]
 [2 3 4 6]
 [0 1 3 7]
 [0 2 5 5]]


In [19]:
print(now)
print(np.argsort(now,axis=0))

[[1 3 5 5]
 [2 3 4 6]
 [0 1 3 7]
 [0 2 5 5]]
[[2 2 2 0]
 [3 3 1 3]
 [0 0 0 1]
 [1 1 3 2]]


In [20]:
a=np.arange(16).reshape(4,4)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [22]:
print(np.argwhere(a==100)) 

[]


#### 在一个矩阵中，找出特定元素的索引来，使用 np.argwhere() 操作

In [30]:
a[0][0]=15
print(np.argwhere(a==15))  # 这个就是一点的是

[[0 0]
 [3 3]]
