# 有一个原则，一个变量不能出两次，最后还要转化成为python脚本文件，还有用print()进行输出 

## numpy基本属性

In [1]:
import numpy as np
a=np.arange(0,15).reshape(3,5)   #   np.arange(xx范围),创建一维array 数组,现在还不是矩阵，一些操作不能使用
b=np.arange(4)
print(a)
print(a.T)
print("--------")
print(b.T)   #array 数组，不能使用.T  转置矩阵


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
--------
[0 1 2 3]


## 使用 x.ndim 查询矩阵的维数量

In [2]:
print(a.ndim)   #ndim

2


## 使用x.shape 查询详细的信息，返回元组，查看维度


In [3]:
print(a.shape)

(3, 5)


### size输出元素个数 

In [4]:
print(a.size)    #  输出元素的个数

15


## numpy.array 数据访问

In [5]:
print(a)
b=np.arange(10)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(b[-1],b[0],b[1]) 

9 0 1


In [7]:
#对于多维数组，使用下标索引
print(a[2][4])    #不推荐这种东西
print(a[2,4])     #推荐这种索引输出

14
14


## 切片，多维的矩阵，基本是二维矩阵，
#### 中间,分割， 前面是0轴， 后面是1轴

In [8]:
print(b[0::2])    #切片的步长

[0 2 4 6 8]


In [9]:
print(a)   
print("---")
print(a[:2,:5:2])   #2X5矩阵， 最后一个参数  步长, ***

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---
[[0 2 4]
 [5 7 9]]


In [10]:
print(a[:2][:3])   #解析错误，应该是 2X3的一个数组，错误输出成为整个的前三个，
#不推荐使用，太乱了

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 在处理numpy数组的时候，使用[x,x] 的形式进行输出，中间符号为   维数分隔符, 注意

In [11]:
print(a)
print("-----")
print(a[::-1,:3:])           #整个矩阵进行反转，

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----
[[10 11 12]
 [ 5  6  7]
 [ 0  1  2]]


## 子矩阵
## 行：a[0,:]
## 列:  a[:,0]

In [12]:
print(a[0,:])   # 行向量
print(a[:,0])   #列向量
print(a[:,0].ndim)


[0 1 2 3 4]
[ 0  5 10]
1


### 对于numpy，原矩阵和切片矩阵，会互相影响到，所以注意

In [13]:
x=a[:2,:3]
print(x)
x[0,0]=123
print(x)
print(a)

[[0 1 2]
 [5 6 7]]
[[123   1   2]
 [  5   6   7]]
[[123   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


## 创建一个与原矩阵不相关的一个子矩阵
## 使用copy() 操作重新建立一个子矩阵

In [14]:
now=a[:2,:3].copy()
now[0,0]=999
print(now)
print(a)   #没有进行修改，达到预期效果

[[999   1   2]
 [  5   6   7]]
[[123   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


## reshape
## 对维度进行改变，改变矩阵的规模 

In [15]:
print(now.reshape(3,2))   #确实重要，不会改变
print(now)   #一个东西

[[999   1]
 [  2   5]
 [  6   7]]
[[999   1   2]
 [  5   6   7]]


###  一维numpy .reshape(10) 和reshape(1,10) ,是不一样的 注意

In [16]:
now1=now.reshape(1,6)
print(now1)
print(now1.ndim)

[[999   1   2   5   6   7]]
2


### reshape(a,-1) ,改为一个东西，a是被元素数量整除的
### reshape(-1,a) 改为一个行向量，a是元素数量

In [18]:
print(now1.reshape(6,-1))
print(now1.reshape(-1,6))


[[999]
 [  1]
 [  2]
 [  5]
 [  6]
 [  7]]
[[999   1   2   5   6   7]]


In [21]:
a=np.arange(16).reshape(4,4)   #   就是0-15 个数，然后再进行reshape 操作
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [29]:
a=np.array([1,2,3,4])                  #array 操作，基本的操作
b=np.array(range(3))
c=np.array([i for i in range(10)])
print(a)
print(b)
print(c)

[1 2 3 4]
[0 1 2]
[0 1 2 3 4 5 6 7 8 9]


#### 随机数  np.random

In [42]:
#   random.randint()
np.random.seed(666)
a=np.random.randint(0,100,size=(10,3))
print(a)

[[ 2 45 30]
 [62 70 73]
 [30 36 61]
 [91 94 51]
 [60 95 28]
 [14 97 63]
 [16 46 39]
 [69 82 76]
 [79 13 69]
 [20 11 24]]


In [51]:
np.random.rand(3,3)        #这个是0 1 之间的
np.random.randn(3,3)       #这个是0 1正态分布的

array([[-0.24332703, -0.47064834,  1.09057819],
       [ 1.2267939 ,  0.25893563, -1.44545669],
       [-0.26378654,  1.71971234,  0.4855902 ]])

In [60]:
np.random.uniform(0,100,size=(3,3))           #指定范围的 用法

array([[75.70392187,  1.76321773, 51.54614289],
       [ 7.37090471, 73.5188602 , 81.57745349],
       [91.42806507, 88.24575998, 14.15266311]])

In [89]:
np.random.random(size=(3,3))   #0 1 之间分布

array([[0.80639973, 0.4304664 , 0.32719931],
       [0.02417211, 0.20048362, 0.04169022],
       [0.58674692, 0.02133903, 0.0771109 ]])

In [98]:
np.random.normal(size=(3,3))

array([[-0.43313974, -1.00100766,  1.06047532],
       [-2.1463905 ,  0.76799933,  0.61189934],
       [-0.34815101,  0.09580047,  2.06814012]])