In [1]:
import numpy as np

### random.random()    是一个0~1 之间的数据，中间参数为 维数, random.random((x,y)) 为二维矩阵
#### random.random(x)   是一个一维向量，

In [30]:
np.random.random((1,10))           

array([[0.16288884, 0.34925418, 0.98089821, 0.26241115, 0.90947647,
        0.71883221, 0.40288541, 0.59634222, 0.33717999, 0.48924314]])

In [12]:
np.random.random((2,2))

array([[0.83337163, 0.10041713],
       [0.18779998, 0.23135433]])

### random.rand(d1,d2,d3..)     是一个0~1之间的数据 ，中间参数为 维数,  只要是两位的，就是二维矩阵，
##### 其中写出一位数字 是一维向量

In [39]:
np.random.rand(1,3)   

array([[0.22365304, 0.28830301, 0.66738759]])

# np.random.randn()   标准的正态分布，规则与上面的一样。 

In [42]:
np.random.randn(10)     

array([-1.40971698, -1.43648642, -0.76643245, -0.9882721 , -0.44200398,
       -0.54970629,  0.32445978, -0.82157105,  0.00317702,  0.78117946])