In [2]:
import numpy as np
import pandas as pd

##### dot是遵循矩阵乘法法则的
#####   普通号 X 既有矩阵乘法的又有逐渐的元素进行相乘

### X(*)相乘

####  多维array与向量之间的相乘，向量会扩展为高维的，然后再进行逐元素的相乘，最后的结果也是高维的

In [89]:
a=np.array([       
    [1],
    [2],
    [3]
])       
b=np.array([2,3,4])     #将b扩展成 了一个 二维的东西3X3 的数组，然后再进行逐元素的相乘       
a*b    #

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

#### 向量之间的相乘，两个向量一样的话，就是逐元素相乘。一个向量数量是1的话，就会将这个数量为1的向量元素 与另一个向量元素，一个个相乘

In [91]:
a=np.array([1,2,3,4])
b=np.array([3])
a*b

array([ 3,  6,  9, 12])

####  高维array与高维 array 之间的相乘。高维array之间对应元素的乘积，  低维的是可以扩展成为高维的数组

In [85]:
np.random.seed(11)
a=np.arange(16).reshape(4,4)        # 这个也是需要扩展的，
b=np.random.randint(10,size=(4,4))
print(a)
print(b)
print(a*b)        #  对应的元素相乘，不是遵循的矩阵乘法

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[9 0 1 7]
 [1 7 2 8]
 [0 0 4 2]
 [1 5 5 7]]
[[  0   0   2  21]
 [  4  35  12  56]
 [  0   0  40  22]
 [ 12  65  70 105]]


### 下面是 dot 使用方法

####  规则的矩阵之间的乘法，输入的是规则的，列和行相同

In [95]:
a=np.arange(16).reshape(4,4)
b=np.arange(8).reshape(4,2)
a.dot(b)

array([[ 28,  34],
       [ 76,  98],
       [124, 162],
       [172, 226]])

##### 下面有一个反常的例子，就是一点的是

In [103]:
a=np.arange(16).reshape(4,4)  
b=np.array([1,2,3,4])
print(a)        
print(b)

a.dot(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[1 2 3 4]


array([ 20,  60, 100, 140])

In [106]:
a=np.array([      #2X2 
    [1,2],
    [3,4]
])
b=np.array([      #2X1
    [2],
    [3]
])
a.dot(b)

array([[ 8],
       [18]])