###  超参数：在算法运行前需要决定的参数
### 模型参数：算法过程中学习的参数
### 调参数，调的是超参数

In [1]:

import numpy as np
import matplotlib as mpl
import pandas as pd
import sklearn
from math import sqrt
import tensorflow
import matplotlib.pyplot as plt
from collections import Counter

In [78]:
from sklearn import datasets
iris=datasets.load_digits()


In [79]:
x=iris.data 
y=iris.target

In [81]:
print(x)
print(y) 
print(x.shape)
print(y.shape)



[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]
(1797, 64)
(1797,)


In [105]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split
a=KNeighborsClassifier(6)
x_train, x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=666)

In [106]:
a.fit(x_train,y_train)
ans=a.predict(x_test)
print(ans)

[8 1 3 4 4 0 7 0 8 0 4 6 1 1 2 0 1 6 7 3 3 6 5 2 3 4 0 2 0 3 0 8 7 2 3 5 1
 3 1 5 8 6 2 6 3 1 3 0 0 4 9 9 2 8 7 0 5 4 0 9 5 5 8 7 4 2 8 8 7 1 4 3 0 2
 7 2 1 2 4 0 9 0 6 6 2 0 0 5 4 4 3 1 3 8 6 4 4 7 5 6 8 4 8 4 6 9 7 7 0 8 8
 3 9 7 1 8 4 2 7 0 0 4 9 6 7 3 4 6 4 8 4 7 2 6 9 5 8 7 2 5 5 9 7 9 3 1 9 4
 4 1 5 1 6 4 4 8 1 6 2 5 2 1 4 4 3 9 4 0 6 0 8 3 8 7 3 0 3 0 5 9 2 7 1 8 1
 4 3 3 7 8 2 7 2 2 8 0 5 7 6 7 3 4 7 1 7 0 9 2 8 9 3 8 9 1 1 1 9 8 8 0 3 7
 3 3 4 8 2 1 8 6 0 1 7 7 5 8 3 8 7 6 8 4 2 6 2 3 7 4 9 3 5 0 6 3 8 3 3 1 4
 5 3 2 5 6 9 6 9 5 5 3 6 5 9 3 7 7 0 2 7 9 9 9 2 5 6 1 9 6 9 7 7 4 5 0 0 5
 3 8 4 4 3 2 5 3 2 2 3 0 9 8 2 1 4 0 6 2 8 0 6 4 9 9 8 3 9 8 6 3 2 7 9 4 2
 7 5 1 1 6 1 0 4 5 2 9 0 3 3 0 7 4 8 5 9 5 9 5 0 7 9 8]


In [107]:
print(sum(ans==y_test)/len(x_test))

0.9888888888888889


In [108]:
a.score(x_test,y_test)

0.9888888888888889

##  下面就是使用 sklearn 的一些掉包东西，这个得记住，不然不知道怎么做

In [109]:
import numpy as np
from matplotlib.pyplot import plot
import matplotlib as mpl
from math import sqrt
from collections import Counter
from sklearn.model_selection import train_test_split  # 使用
from sklearn.neighbors import KNeighborsClassifier  


In [110]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1437, 64)
(1437,)
(360, 64)
(360,)


####  第一个超参数的选取，
####   1. K值的不同,寻找最好的K

In [111]:
best_k=-1
best_ans=0

for k in range(1,11):
    a=KNeighborsClassifier(k)
    a.fit(x_train,y_train)
    ans=a.score(x_test,y_test)
    if ans >best_ans:
        best_ans=ans
        best_k=k

print(best_k)
print(best_ans)


4
0.9916666666666667


#### 2.考虑点之间的距离了,  ['uniform','distance']

In [112]:
best_k=-1
best_ans=0
best_method=""
for method in ['uniform','distence']:
    for k in range(1,11):
        a=KNeighborsClassifier(k)
        a.fit(x_train,y_train)
        ans=a.score(x_test,y_test)
        if ans >best_ans:
            best_ans=ans
            best_k=k
            best_method=method

print(best_k)
print(best_ans)
print(best_method)

4
0.9916666666666667
uniform


#### 明可夫斯基距离

In [122]:
%%time
best_k=-1
best_ans=0
best_p=-1


for k in range(1,11):
    for p in range(1,6):
        a=KNeighborsClassifier(k,weights='distance',p=p)
        a.fit(x_train,y_train)
        ans=a.score(x_test,y_test)
        if ans >best_ans:
            best_ans=ans
            best_k=k
            best_p=p
                
            

print(best_k)
print(best_ans)
print(best_p)

3
0.9888888888888889
2
Wall time: 19.8 s


### 总结
####  weights="uniform"   就不会牵扯到p
####  distance 就会牵扯到 p
#### 之间相互依赖的情况